{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "35982aa0",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\\Untitled_381-390.ipynb : 0.2897796630859375  мегобайт  2024-10-15 22:17:17.042536\n"
     ]
    }
   ],
   "source": [
    "import os;import math;import sys;import datetime;\n",
    "var='\\\\Untitled_381-390.ipynb'\n",
    "print (var,':',os.path.getsize(os.path.abspath(os.curdir)+var)/math.pow(2, 20),' мегобайт ',datetime.datetime.now())"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "97ca01f7",
   "metadata": {},
   "source": [
    "- Каждому сотруднику соответствуют имя и показатель эффективности. Подсчитайте общую сумму, выплачиваемую в виде бонусов, если каждый сотрудник получает бонус в размере $ 100 в случае, когда его показатель эффективности равен 3 или выше.\n",
    "- Каждому кулинарному рецепту соответствуют название, список ингредиентов (некоторые из них включают мясные продукты) и приблизительное время приготовления. Найдите среднюю оценку времени, требуемого для приготовления одного из вегетарианских блюд.\n",
    "\n",
    "Ещё больше книг по Java в нашем телеграм канале: https: //t.me/javalib\n",
    "\n",
    "Стр. 382\n",
    "\n",
    "----------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5cdbaffb",
   "metadata": {},
   "source": [
    "# Глава 13\n",
    "Как сохранить хорошую мину при плохой игре В ЭТОЙ ГЛАВЕ…\n",
    "- Восстановление нормального состояния программы при возникновении нестандартных ситуаций\n",
    "- Повышение отказоустойчивости кода\n",
    "- Определение пользовательских классов исключений\n",
    "\n",
    "9 сентября 1945 года. Безымянный жучок проник в механическое реле компьютера Mark II Гарвардского университета и нарушил его работу. Это был первый зарегистрированный случай краха компьютера вследствие проникновения в него живого насекомого. Впоследствии слово \"bug\" (жучок), означающее ошибку в работе программы, стало чрезвычайно популярным и породило ряд производных словоформ, таких как \"debug\" (отладка), \"buggy\" (ненадежный) и др. 9 апреля 1957 года. Герберт Брайт, менеджер Центра обработки данных компании Westinghouse (Питтсбург), получил тяжелую посылку, заполненную толстыми пачками перфокарт. В те времена это было эквивалентно получению электронного письма или компакт-диска. Посылка пришла от команды разработчиков компилятора FORTRAN - первого высокоуровневого языка программирования. Интернета тогда еще и в помине не было, поэтому обмен программным обеспечением происходил посредством старой доброй почтовой службы."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a13f5be3",
   "metadata": {},
   "source": [
    "Брайт запустил полученный компилятор на своем компьютере IBM 704 и обработал с его помощью небольшую программу на языке FORTRAN. Это была сложнейшая техническая задача. Брайту помогал целый отдел сотрудников. Машина IBM 704 занимала огромную комнату площадью 185 м2, специально построенную для нее. Транзисторов тогда еще не было. Машина работала на вакуумных электронных лампах, потреблявших приличную мощность. Оперативная память машины имела объем 32 Кбайт. Операционная система загружалась с бумажной перфоленты перед запуском каждой программы, которая обычно выполнялась от двух до четырех часов. После всех подготовительных работ и ожиданий компилятор вернул единственное сообщение об ошибке - в одном из операторов программы отсутствовала запята. Брайт изготовил новую перфокарту вместо ошибочной, и программа заработала, как от нее ожидалось. Это был первый зарегистрированный случай отладки высокоуровневого кода пользователями компилятора. 22 июля 1962 года. Запуск космического аппарата \"Mariner I\" с мыса Канаверал. Это был первый в истории космический аппарат, предназначенный для полета на другую планету Солнечной системы (Венера). Через четыре минуты после запуска аппарат развалился на части вследствие неполадок в системе управления. Как оказалось, в формуле расчета скорости ракеты-носителя был пропущен дефис. Приблизительно в это же время в программном обеспечении NASA, предназначенном для управления орбитальным полетом, была обнаружена ошибочная инструкция DO 10 I=1.10 (вместо DO 10 I=1, 10). Точка вместо запятой превратила цикл for (int i=1; i<=10; i++) в оператор присваивания do10i = 1.10. 1 января 2000 года. \"Проблема 2000-го года\" (проблема Y2K) -- ожидание того, что нормальная работа старых программ, оперирующих лишь двумя последними цифрами в обозначении года, может быть нарушена после наступления новогодней ночи 2000 года, - посеяла панику во всем мире.Приводимые в этом разделе исторически достоверные факты заимствованы из следующих источников. Группа новостей \"Computer Folklore\": https://groups.google.com/forum/#!forum/alt.folklore.computers Бесплатный онлайновый словарь \"Dictionary of Computing\": http://foldoc.org Журнал Computer: http://www.computer.org/computermagazine/ Другие веб-страницы IEEE: www.computer.org\n",
    "\n",
    "Стр. 384\n",
    "\n",
    "----------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2cb10540",
   "metadata": {},
   "source": [
    "# Обработка исключений \n",
    "Предположим, вы составляете инвентарную опись товара. Это означает, что вам нужно пересчитать коробки и зафиксировать их количество в журнале, на листке бумаги или в компьютерной памяти, введя данные с помощью клавиатуры. Остановимся на последнем варианте. Вы подсчитываете количество коробок стоимостью 3,25 доллара каждая и вводите его с клавиатуры в программу, которая умножает стоимость одной коробки на их количество. Код программы показан в листинге 13.1. Сама по себе программа, казалось бы, работает безупречно. Если ввести целое число, она отобразит на консоли правильный результат. Однако пользователь может ошибиться. Что будет, если пользователь введет не целое число (например, 3.5)? Или, совсем уж размечтавшись о посторонних вещах, введет слово три вместо числа 3? Очевидно, программа потерпит крах (рис. 13.1). Вы как программист должны предусмотреть подобные случаи. При любых входных данных программа должна сообщить пользователю об ошибке и предложить ее исправить."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "70b46bb2",
   "metadata": {},
   "source": [
    "    Листинг 13.1. Подсчет количества коробок\n",
    "    import static java.lang.System.out;\n",
    "    import java.util.Scanner;\n",
    "    import java.text.NumberFormat;\n",
    "    public class InventoryA\n",
    "    {\n",
    "        public static void main(String args[])\n",
    "        {\n",
    "            final double boxPrice = 3.25;\n",
    "            Scanner keyboard = new Scanner(System.in);\n",
    "            NumberFormat currency = NumberFormat.getCurrencyInstance();\n",
    "            out. print (\"Сколько коробок вы насчитали?\");\n",
    "            String numBoxesIn = keyboard.next ();\n",
    "            int numBoxes = Integer.parseInt (numBoxesIn);\n",
    "            out. print (\"Общая стоимость равна: \");\n",
    "            out.println(currency.format (numBoxes * boxPrice));\n",
    "            keyboard.close ();\n",
    "        }\n",
    "    }\n",
    "Стр. 385\n",
    "\n",
    "---------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "619d4b21",
   "metadata": {},
   "source": [
    "    Сколько коробок вы насчитали? Общая стоимость равна: 9,75 руб.\n",
    "    Сколько коробок вы насчитали? 3.5\n",
    "    Exception in thread \"main\" java.lang.NumberFormatException: For input string: \"3.5\"\n",
    "    at java. lang. NumberFormatException. forInputString(Unknown Source)\n",
    "    at java lang. Integer.parseInt(Unknown Source)\n",
    "    at java. lang Integer.parseInt(Unknown Source)\n",
    "    at InventoryA. main(InventoryA. java: 14)\n",
    "    Сколько коробок вы насчитали? три\n",
    "    Exception in thread \"main\" java lang NumberFormatException: For input string: \"три\" at java. lang. NumberFormatException.forInputString(Unknown Source)\n",
    "    at java lang Integer parseInt(Unknown Source)\n",
    "    at java. lang.Integer. parseInt(Unknown Source)\n",
    "    at InventoryA. main(InventoryA. java: 14)\n",
    "Рис. 13.1. Результаты трехвыполнений листинга 13.1"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2e1b6651",
   "metadata": {},
   "source": [
    "Ключ к устранению ошибки - имя исключения java.lang. NumberFormat Exception (неправильный формат числа), отображенное на консоли рабочей средой Eclipse. Оно означает, что класс исключения NumberFormatException находится в пакете java.lang. Вызов метода Integer.parseInt каким-то образом привел к появлению указанного исключения. Краткое описание метода Integer. parseInt можно найти в главе 11.\n",
    "\n",
    "В язык Java встроен механизм обработки исключений. Используя этот механизм, программа на Java может обнаружить, что операцию нельзя выполнить, и отреагировать на это созданием некоего совершенно нового объекта. Согласно официальной терминологии этот процесс называется генерированием исключения. Упомянутый новый объект - объект исключения (экземпляр класса Exception) -- словно обжигающая руки картофелина, передается от одного участка кода к другому, пока где-то в коде не будет принято решение перехватить исключение. Когда исключение перехвачено, программа выполняет код восстановления, отменяет исключение и переходит к выполнению следующей нормальной инструкции, как будто ничего не случилось (рис. 13.2). Перехват и обработка исключений выполняются с помощью нескольких ключевых слов Java.\n",
    "\n",
    "Стр. 386\n",
    "\n",
    "-----------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a5b41e02",
   "metadata": {},
   "source": [
    "- throw (сгенерировать исключение). Создает новый объект исключения.\n",
    "- throws (генерирует исключение). Директива, передающая необработанное исключение вызывающему методу.\n",
    "- try (попытаться выполнить). Блок кода, в котором возможно возникновение исключения. Обычно в него включают вызовы методов, в теле которых могут возникать исключения.\n",
    "- catch (перехватить исключение). В блоке catch находится код, который обрабатывает исключение, отменяет его и осуществляет возврат в обычный поток управления."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "18a5eff8",
   "metadata": {},
   "source": [
    "    void methodl ()\n",
    "    {\n",
    "        try{method2();}\n",
    "        catch (Exception e){}\n",
    "    }\n",
    "    void method2() throws Exception { method3();}\n",
    "    void method3() throws Exception { method4() ;}\n",
    "    void method4() throws Exception { throw new Exception();}\n",
    "Рис. 13.2. Генерирование, передача и перехват исключения"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "d91cd040",
   "metadata": {},
   "source": [
    "Итак, истина где-то рядом. С помощью определенной цепи событий, подобной показанной на рис. 13.2, метод Integer.parseInt может генерировать исключение NumberFormatException. Как только вызывается метод Integer. parseInt, вам передается исключение NumberFormatException.\n",
    "- совет - В документации Java API есть раздел, посвященный методу parseInt. В нем сказано, что, если входная строка не содержит целое число, метод генерирует исключение NumberFormatException, что мы и видим на рис. 13.1.\n",
    "\n",
    "Итак, если в вас достаточно мужества, вы должны сами организовать перехват исключения, чтобы другой код мог спокойно выполнять свою обычную работу. Измененный вариант программы приведен в листинге 13.2.\n",
    "\n",
    "Стр. 387\n",
    "\n",
    "----------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "32d09171",
   "metadata": {},
   "source": [
    "    Листинг 13.2. Героический подсчет количества коробок\n",
    "    import static java.lang.System.out;\n",
    "    import java.util.Scanner;\n",
    "    import java.text.NumberFormat;\n",
    "    public class InventoryB\n",
    "    {\n",
    "        public static void main(String args[])\n",
    "        {\n",
    "            final double boxPrice = 3.25;\n",
    "            Scanner keyboard = new Scanner(System. in);\n",
    "            NumberFormat currency = NumberFormat.getCurrencyInstance();\n",
    "            out.print (\"Сколько коробок вы насчитали?\");\n",
    "            String numBoxesIn = keyboard.next ();\n",
    "            try\n",
    "            {\n",
    "                int numBoxes = Integer.parseInt (numBoxesIn);\n",
    "                out.print(\"Общая стоимость равна: \");\n",
    "                out.println(currency.format (numBoxes * boxPrice));\n",
    "            } catch (NumberFormatException e) {out.println(\"Это не целое число.\");}\n",
    "            keyboard.close();\n",
    "        }\n",
    "    }"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a9d51371",
   "metadata": {},
   "source": [
    "На рис. 13.3 показаны три сеанса работы программы, приведенной в листинге 13.2. Когда пользователь вместо 3 вводит три, программа отвечает: Это не целое число. Трюк состоит в помещении вызова Integer.parseInt в блок try. Компьютер наблюдает за исключениями в инструкциях, находящихся в данном блоке. Если происходит исключение, компьютер прекращает выполнение блока try и немедленно передает управление блоку catch. Последующие инструкции блока try не выполняются. В листинге 13.2 управление в случае исключения передается блоку catch (NumberFormatException e). В блоке catch компьютер отображает сообщение об ошибке с помощью метода println. После этого компьютер продолжает выполнять программу, начиная с первой инструкции после блока catch. В блок try компьютер больше не возвращается.\n",
    "- технические подробности - Вся конструкция try catch, включая блок try, блок catch и весь код, который вы в них включите, называется инструкцией try. Иногда, для усиления, я называю ее инструкцией try catch.\n",
    "\n",
    ">Сколько коробок вы насчитали? Общая стоимость равна: 9,75 руб.\n",
    "\n",
    ">Сколько коробок вы насчитали? три Это не целое число.\n",
    "\n",
    ">Сколько коробок вы насчитали? -25 Общая стоимость равна: -81,25 руб.\n",
    "\n",
    "Рис. 13.3. Программа обработала исключение, сгенерированное при втором запуске\n",
    "\n",
    "Стр. 388\n",
    "\n",
    "----------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5e9d1b0a",
   "metadata": {},
   "source": [
    "# Параметр блока catch\n",
    "Обратите внимание на содержимое в круглых скобках (NumberFormat Exception e) после ключевого слова catch в листинге 13.2. Все это напоминает передачу списка параметров методу, не правда ли? Фактически каждый блок catch - это мини-метод со своим списком параметров. Операционная система передает блоку catch имя типа сгенерированного исключения. В листинге 13.2 мы ничего не делаем с полученным параметром, однако при необходимости его можно использовать. Сгенерированное исключение - это экземпляр класса NummberFormatException. Когда исключение перехвачено блоком catch, параметр е ссылается на объект исключения. Иными словами, объект е содержит информацию об исключении. Можно также вызывать методы объекта исключения.\n",
    "\n",
    "    } catch (NumberFormatException e) {\n",
    "        out.println(\"Cообщение: ***\" + e.getMessage() + \"***\");\n",
    "        e.printStackTrace () ;\n",
    "    }\n",
    "\n",
    "Результат работы программы InventoryB с этим новым блоком catch показан на рис. 13.4. Метод getMessage возвращает детализирующую информацию об исключении (в данном случае строку Cообщение: ***For input string: \"три\"***), а метод printStackTrace выводит на консоль дополнительную информацию о стеке вызовов - перечень методов, выполняющихся в момент генерирования исключения (на рис. 13.4 это методы Integer.parseInt и main). Информация, выводимая обоими методами, упрощает поиск источника ошибки.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4133499d",
   "metadata": {},
   "source": [
    "- технические подробности - При смешивании вызовов System.out.println и printStackTrace последовательность вывода информации на консоль непредсказуема. Например, на рис. 13.4 текст Сообщение: может появиться после\n",
    "\n",
    "информации о стеке вызовов методов. Если последовательность вывода важна для вас, замените\n",
    ">out.println(\"Сообщение: ***\"\n",
    "\n",
    "вызовом\n",
    ">System.err.println(\"Сообщение ***\"\n",
    "\n",
    "Стр. 389\n",
    "\n",
    "---------"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "da16ad6f",
   "metadata": {},
   "source": [
    "    Сколько коробок вы насчитали? три\n",
    "    Сообщение: **\"For input string: \"три\"***\n",
    "    java.lang.NumberFormatException: For input string: \"три\"\n",
    "    at java. lang. NumberFormatException.ForInputString(Unknown Source)\n",
    "    at java. lang. Integer.parseInt(Unknown Source)\n",
    "    at java. lang. Integer. parseInt(Unknown Source)\n",
    "    at Inventory8.main(InventoryB.java: 16)\n",
    "    \n",
    "Рис. 13.4. Результат вызова методов, относящихся к объектуисключения"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "12d48411",
   "metadata": {},
   "source": [
    "# Типы исключений\n",
    "А что еще сегодня может пойти не так? Невозможность прочитать число - не единственный тип ошибки. Соответственно, кроме NumberFormatException, существует много других типов исключений. Вы даже можете создать собственное исключение, которое в этом случае будет называться пользовательским. Хотите попробовать? Взгляните на листинги 13.3 и 13.4.\n",
    "\n",
    "    Листинг 13.3. Создание пользовательского исключения\n",
    "    @SuppressWarnings (\"serial\")\n",
    "    class OutOfRangeException extends Exception{}"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "00a518c3",
   "metadata": {},
   "source": [
    "    Листинг 13.4. Генерирование пользовательского исключения\n",
    "    import static java.lang.System.out;\n",
    "    import java.util.Scanner;\n",
    "    import java.text.NumberFormat;\n",
    "    public class InventoryC\n",
    "    {\n",
    "        public static void main(String args[])\n",
    "        {\n",
    "            final double boxPrice = 3.25;\n",
    "            Scanner keyboard = new Scanner(System.in);\n",
    "            NumberFormat currency = NumberFormat.getCurrencyInstance();\n",
    "            out.print(\"Сколько коробок вы насчитали? \"); \n",
    "            String numBoxesIn = keyboard.next();\n",
    "            try\n",
    "            {\n",
    "             \n",
    "             int numBoxes = Integer.parseInt (numBoxesIn);\n",
    "                if (numBoxes < 0) {throw new OutOfRangeException() ; }\n",
    "                out.print(\"Общая стоимость равна: \");\n",
    "                out.println(currency.format (numBoxes * boxPrice));\n",
    "            } \n",
    "                catch (NumberFormatException e) {out.println(\"Это не число.\");}\n",
    "                catch (OutOfRangeException e) \n",
    "            {\n",
    "                out.print (numBoxesIn) ;\n",
    "                out.println(\"? Это невозможно!\");\n",
    "            }\n",
    "            keyboard.close () ;\n",
    "        }\n",
    "    }\n",
    "    \n",
    "Стр. 390\n",
    "\n",
    "---------"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
